{{- range $secretSuffix, $secretContent := .Values.auth }}
{{- if and (empty $secretContent.existingSecret) (ne $secretContent.enabled false) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onyx-stack.secretName" . }}
type: Opaque
stringData:
  {{- range $name, $value := $secretContent.values }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
